// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQCpYlWj61pK4vpEK0kC6tPTssOwlz4pY',
    appId: '1:672678517697:web:48623363b2b8a3d6bbad40',
    messagingSenderId: '672678517697',
    projectId: 'sync-clock-project',
    authDomain: 'sync-clock-project.firebaseapp.com',
    storageBucket: 'sync-clock-project.firebasestorage.app',
    measurementId: 'G-8GF9KCW5P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO4yMNSvDyek90RMYcjxpnrxS3SM0kaIg',
    appId: '1:672678517697:android:32d54b60e226518abbad40',
    messagingSenderId: '672678517697',
    projectId: 'sync-clock-project',
    storageBucket: 'sync-clock-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgWit7Z8Wb2e885a6saVT9J-qW8IE8cSg',
    appId: '1:672678517697:ios:be4febba3d0688eebbad40',
    messagingSenderId: '672678517697',
    projectId: 'sync-clock-project',
    storageBucket: 'sync-clock-project.firebasestorage.app',
    iosBundleId: 'com.example.syncClock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgWit7Z8Wb2e885a6saVT9J-qW8IE8cSg',
    appId: '1:672678517697:ios:be4febba3d0688eebbad40',
    messagingSenderId: '672678517697',
    projectId: 'sync-clock-project',
    storageBucket: 'sync-clock-project.firebasestorage.app',
    iosBundleId: 'com.example.syncClock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQCpYlWj61pK4vpEK0kC6tPTssOwlz4pY',
    appId: '1:672678517697:web:bb4525def944cbc4bbad40',
    messagingSenderId: '672678517697',
    projectId: 'sync-clock-project',
    authDomain: 'sync-clock-project.firebaseapp.com',
    storageBucket: 'sync-clock-project.firebasestorage.app',
    measurementId: 'G-QLYFETXC0M',
  );
}
